name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check for changes in non-doc files
        id: check_changes
        run: |
          git diff --name-only HEAD^ HEAD > changes.txt
          if grep -qvE '^README.md$' changes.txt; then
            echo "Changes detected in non-doc files."
          else
            echo "Only doc files changed, stopping job."
            exit 0
          fi

      - name: Setup Pages
        if: success()  # Only run if the previous step did not exit
        uses: actions/configure-pages@v5

      - name: Upload artifact
        if: success()  # Only run if the previous step did not exit
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: '.'

      - name: Deploy to GitHub Pages
        if: success()  # Only run if the previous step did not exit
        id: deployment
        uses: actions/deploy-pages@v4
